name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]


env:
  PORT : 4000
  GithubClientID  :  nfasjaskjd
  GithubClientSecret  :  sdlkdasjlkads

  GoogleClientID  : dsasdadsajn
  GoogleClientSecret :  notneededfortest

  SESSION_SECRET  :  klsadnjfan@)!)@LSAMnfwaaskd---019-23

  CALLBACK_GITHUB_PREFIX : github/callback
  CALLBACK_GOOGLE_PREFIX : google

  CALLBACK_URL_GITHUB : http://localhost:4000/auth/github/callback
  CALLBACK_URL_GOOGLE : http://localhost:4000/auth/google

  DATABASE_URI : ${{ secrets.DATABASE_URI }}
  REDIS_URI : ${{ secrets.REDIS_URI }}

  TESTING_DATABASE_URI : ${{ secrets.DATABASE_URI }}

  CORS_ORIGIN :  http://localhost:5173

  CLOUD_API_SECRET : ${{ secrets.CLOUD_API_SECRET }}
  CLOUD_NAME  :  ${{ secrets.CLOUD_NAME }}
  CLOUD_API_KEY  :  ${{ secrets.CLOUD_API_KEY }}

  SUCCESS_REDIRECT_URL  : http://localhost:4000/auth/pro 
  FAILED_REDIRECT_URL  : http://localhost:4000/auth/login

jobs:
  simple_deployment_pipeline:
    if: ${{ github.event_name == 'push' }}
    environment: testing 
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Check lint
        run: bun run eslint
      - name: Check env
        run: echo $CLOUD_NAME
      - name:  tests
        run: bun run test
